[package]
name = "rook"
version = "0.1.0"
authors = ["Alex Lagerstedt <alex.lagerstedt@gmail.com>"]

[[bin]]
name = "rook-engine"
path = "src/uci.rs"

[[bin]]
name = "rook"
path = "src/main.rs"

[dependencies]
bitflags = "0.5.0"
rand = "0.3.0"
ansi_term = "0.7"
lazy_static = "0.1.*"
time = "0.1.*"
